Sulok Pandey

TO Do File 

4.1 Exercise on Functions:

In [6]:
#Task1
def convert(unit, value):
    if unit == 'a':
        return value * 3.28084  
    elif unit == 'b':
        return value / 3.28084  
    elif unit == 'c':
        return value * 2.20462  
    elif unit == 'd':
        return value / 2.20462  
    elif unit == 'e':
        return value * 0.264172  
    elif unit == 'f':
        return value / 0.264172  
    else:
        return None

print("a: Meters to Feet\nb: Feet to Meters\nc: Kilograms to Pounds\nd: Pounds to Kilograms\ne: Liters to Gallons\nf: Gallons to Liters")
choice = input("Enter choice (a-f): ").lower()

value = float(input("Enter value: "))
result = convert(choice, value)
print(f"Converted value: {result:.4f}")


    

a: Meters to Feet
b: Feet to Meters
c: Kilograms to Pounds
d: Pounds to Kilograms
e: Liters to Gallons
f: Gallons to Liters
Converted value: 32.8084


In [7]:
#Task2
def find_sum(numbers):
    return sum(numbers)

def find_average(numbers):
    return sum(numbers) / len(numbers)

def find_maximum(numbers):
    return max(numbers)

def find_minimum(numbers):
    return min(numbers)

def main():
    print("Select an operation:")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    try:
        operation = int(input("which operation do you want to do: "))

        if operation not in [1, 2, 3, 4]:
            print("Invalid selection.")
            return

        numbers_input = input("Enter List of number: ")
        numbers = list(map(float, numbers_input.split()))
        if operation == 1:
            print("Sum:", find_sum(numbers))
        elif operation == 2:
            print("Average:", find_average(numbers))
        elif operation == 3:
            print("Maximum:", find_maximum(numbers))
        elif operation == 4:
            print("Minimum:", find_minimum(numbers))

    except ValueError:
        print("Invalid Input")

if __name__ == "__main__":
    main()


Select an operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Sum: 27.0


4.2

In [8]:
def extract_every_other(lst):
    return lst[::2]

def get_sublist(lst, start, end):
    return lst[start:end+1]

def reverse_list(lst):
    return lst[::-1]

def remove_first_last(lst):
    return lst[1:-1]

def get_first_n(lst, n):
    return lst[:n]

def get_last_n(lst, n):
    return lst[-n:]

def reverse_skip(lst):
    return lst[-2::-2]

lst = [1, 2, 3, 4, 5, 6, 7, 8, 9]
print(extract_every_other(lst))
print(get_sublist(lst, 2, 5))
print(reverse_list(lst))
print(remove_first_last(lst))
print(get_first_n(lst, 4))
print(get_last_n(lst, 3))
print(reverse_skip(lst))



[1, 3, 5, 7, 9]
[3, 4, 5, 6]
[9, 8, 7, 6, 5, 4, 3, 2, 1]
[2, 3, 4, 5, 6, 7, 8]
[1, 2, 3, 4]
[7, 8, 9]
[8, 6, 4, 2]


In [9]:
def flatten(lst):
    flattened = []
    for item in lst:
        if isinstance(item, list):
            flattened.extend(flatten(item))
        else:
            flattened.append(item)
    return flattened

def access_nested_element(lst, indices):
    for index in indices:
        lst = lst[index]
    return lst

def sum_nested(lst):
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total

def remove_element(lst, elem):
    for i in range(len(lst)):
        if isinstance(lst[i], list):
            lst[i] = remove_element(lst[i], elem)
        else:
            if lst[i] == elem:
                lst[i] = None
    return [item for item in lst if item is not None]

def find_max(lst):
    max_val = float('-inf')
    for item in lst:
        if isinstance(item, list):
            max_val = max(max_val, find_max(item))
        else:
            max_val = max(max_val, item)
    return max_val

def count_occurrences(lst, elem):
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        else:
            if item == elem:
                count += 1
    return count

def deep_flatten(lst):
    flattened = []
    for item in lst:
        if isinstance(item, list):
            flattened.extend(deep_flatten(item))
        else:
            flattened.append(item)
    return flattened

def average_nested(lst):
    def recursive_sum_and_count(lst):
        total_sum = 0
        count = 0
        for item in lst:
            if isinstance(item, list):
                nested_sum, nested_count = recursive_sum_and_count(item)
                total_sum += nested_sum
                count += nested_count
            else:
                total_sum += item
                count += 1
        return total_sum, count

    total_sum, count = recursive_sum_and_count(lst)
    
    if count == 0:
        return 0
    else:
        return total_sum / count

In [10]:
lst = [[1, 2], [3, [4, 5]], 6]
print(flatten(lst)) 
print(access_nested_element(lst, [1, 1]))
print(sum_nested(lst)) 
lst2 = [[1, 2], [3, 2], [4, 5]]
print(remove_element(lst2, 2))
print(find_max(lst))
print("Occurrences of 2:", count_occurrences(lst2, 2)) 
lst3 = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
print(deep_flatten(lst3)) 
lst4 = [[1, 2], [3, 4], [5, 6]]
print(average_nested(lst4))

[1, 2, 3, 4, 5, 6]
[4, 5]
21
[[1], [3], [4, 5]]
6
Occurrences of 2: 0
[1, 2, 3, 4, 5, 6, 7, 8]
3.5


Numpy

In [24]:
#problem 1
import numpy as np
empty_array = np.empty((2, 2))
print(empty_array)

ones_array = np.ones((4, 2))
print("\n",ones_array)

shape = (3, 3)
fill_value = 7
filled_array = np.full(shape, fill_value)
print("\n",filled_array)

given_array = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(given_array)
print("\n",zeros_like_array)

ones_like_array = np.ones_like(given_array)
print("\n",ones_like_array)

new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\n",numpy_array)


[[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]]

 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

 [[7 7 7]
 [7 7 7]
 [7 7 7]]

 [[0 0]
 [0 0]]

 [[1 1]
 [1 1]]

 [1 2 3 4]


In [25]:
#problem 2

arr1 = np.arange(10, 50)
print("\n", arr1)

arr2 = np.arange(9).reshape(3, 3)
print("\n", arr2)

arr3 = np.eye(3)
print("\n", arr3)

arr4 = np.random.random(30)
mean_arr4 = arr4.mean()
print("\n", arr4)
print("\nMean", mean_arr4)

arr5 = np.random.random((10, 10))
min_value = arr5.min()
max_value = arr5.max()
print("\n", arr5)
print("\nMinmun", min_value)
print("\nMaximum", max_value)

arr6 = np.zeros(10)
arr6[4] = 1 
print("\n", arr6)

arr7 = np.array([1, 2, 0, 0, 4, 0])
reversed_arr7 = arr7[::-1]
print("\n", reversed_arr7)

arr8 = np.ones((5, 5))
arr8[1:-1, 1:-1] = 0
print("\n", arr8)

arr9 = np.zeros((8, 8), dtype=int)
arr9[1::2, ::2] = 1
arr9[::2, 1::2] = 1
print("\n", arr9)



 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

 [[0 1 2]
 [3 4 5]
 [6 7 8]]

 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

 [0.36187099 0.97780777 0.19014954 0.9236983  0.65486139 0.40565677
 0.26075247 0.44975575 0.35260201 0.95042633 0.17239281 0.97894919
 0.46796775 0.62801133 0.00159569 0.68063599 0.7765102  0.53649366
 0.41798367 0.00753603 0.15546183 0.69838144 0.56606107 0.22327103
 0.73261396 0.71158695 0.89486546 0.86558032 0.61168277 0.49708354]

Mean 0.5384082009633199

 [[0.72140651 0.64266318 0.12663767 0.35094009 0.78035879 0.39078732
  0.12996791 0.45699225 0.19841457 0.23280769]
 [0.24581133 0.22529658 0.31196555 0.46731117 0.85866572 0.31456723
  0.40756826 0.84674909 0.71913779 0.43500471]
 [0.46770579 0.36800747 0.74988933 0.62188342 0.46257556 0.36945601
  0.91596189 0.06104216 0.40333041 0.46671979]
 [0.12409684 0.72877907 0.7464633  0.0565117  0.72313376 0.32896653
  0.6564904  0.53174339 0.33

In [26]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

addition = x + y
print("Addition of x and y:\n", addition)

subtraction = x - y
print("Subtraction of x and y:\n", subtraction)

multiplication_x = x * 2
multiplication_y = y * 3
print("Multiplying x by 2:\n", multiplication_x)
print("Multiplying y by 3:\n", multiplication_y)

dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)

print("Dot product of v and w:", dot_vw)
print("Dot product of x and v:\n", dot_xv)
print("Dot product of x and y:\n", dot_xy)

concatenate_xy_row = np.concatenate((x, y), axis=0)
concatenate_vw_col = np.concatenate((v.reshape(-1, 1), w.reshape(-1, 1)), axis=1)

print("Concatenating x and y along row:\n", concatenate_xy_row)
print("Concatenating v and w along column:\n", concatenate_vw_col)


#concatenate_xv = np.concatenate((x, v), axis=0) 
#The error occurs beacause x is a 2d array and v is 1d array

Addition of x and y:
 [[ 6  8]
 [10 13]]
Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]
Multiplying x by 2:
 [[ 2  4]
 [ 6 10]]
Multiplying y by 3:
 [[15 18]
 [21 24]]
Dot product of v and w: 219
Dot product of x and v:
 [29 77]
Dot product of x and y:
 [[19 22]
 [50 58]]
Concatenating x and y along row:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenating v and w along column:
 [[ 9 11]
 [10 12]]


In [28]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

A_inverse = np.linalg.inv(A)
identity_matrix = np.dot(A, A_inverse)
print("A * A_inverse:\n", identity_matrix)

AB = np.dot(A, B)
BA = np.dot(B, A)
print("AB:\n", AB)
print("BA:\n", BA)

AB_Tp = (np.dot(A, B)).T
BTp_ATp = np.dot(B.T, A.T)

print("Transpose of AB:\n", AB_Tp)
print("\n", BTp_ATp)

A_eq = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B_eq = np.array([[-1], [-3], [9]])
A_inv_eq = np.linalg.inv(A_eq)
X_eq = np.dot(A_inv_eq, B_eq)
print("Solution for x, y, z:\n", X_eq)


A * A_inverse:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
Transpose of AB:
 [[23 51]
 [13 29]]

 [[23 51]
 [13 29]]
Solution for x, y, z:
 [[ 2.]
 [ 1.]
 [-2.]]


In [29]:
#Experiment
import time

In [ ]:
list_a = [i for i in range(1000000)]
list_b = [i for i in range(1000000)]

start_time = time.time()
result_list_addition = [list_a[i] + list_b[i] for i in range(1000000)]
end_time = time.time()
total_time=end_time-start_time
print(total_time)


0.1266310214996338


In [35]:
np_a = np.array(list_a)
np_b = np.array(list_b)

start_time = time.time()
result_np_addition = np_a + np_b
end_time = time.time()
total_time=end_time-start_time
print(total_time)

0.0029859542846679688


In [37]:
start_time = time.time()
result_list_multiplication = [list_a[i] * list_b[i] for i in range(1000000)]
end_time = time.time()
total_time=end_time-start_time
print(total_time)

0.1172175407409668


In [38]:
start_time = time.time()
result_np_multiplication = np_a * np_b
end_time = time.time()
total_time=end_time-start_time
print(total_time)

0.0050051212310791016


In [39]:
start_time = time.time()
dot_product_list = sum(list_a[i] * list_b[i] for i in range(1000000))
end_time = time.time()
total_time=end_time-start_time
print(total_time)

0.10648202896118164


In [40]:
start_time = time.time()
dot_product_np = np.dot(np_a, np_b)
end_time = time.time()
total_time=end_time-start_time
print(total_time)

0.0019941329956054688


In [41]:
matrix_a = [[i + j for i in range(1000)] for j in range(1000)]
matrix_b = [[i + j for i in range(1000)] for j in range(1000)]

start_time = time.time()
result_matrix_multiplication_list = [[sum(matrix_a[i][k] * matrix_b[k][j] for k in range(1000)) for j in range(1000)] for i in range(1000)]
end_time = time.time()
total_time=end_time-start_time
print(total_time)

245.68488574028015


In [42]:
np_matrix_a = np.array(matrix_a)
np_matrix_b = np.array(matrix_b)

start_time = time.time()
result_matrix_multiplication_np = np.matmul(np_matrix_a, np_matrix_b)
end_time = time.time()
total_time=end_time-start_time
print(total_time)

3.5778136253356934
